#pragma once

#include <span>

struct Text {
    const char* JPN;
    const char* ENG;
};

namespace SH1 {
    std::array TreeOffsets = {
        0x31cec, //0x2C
        0x31ed0, //0x4C
        0x31f2c, //0x8C
        0x31f8c, //0xCC
        0x32090  //0x2C
    };

    std::array Tree2C_data = {
        Text{"譲歩", "譲歩"},
        Text{"オープニング", "Opening"},
        Text{"証言台にて", "Witness Stand"},
        Text{"逮捕の瞬間", "Captured"},
        Text{"涼しい横顔", "Composed"},
        Text{"選択肢", "Choices"},
        Text{"疑問への回答", "Answers"},
        Text{"煽った代償", "Price of Aggravation"},
        Text{"東拘", "Tokyo Detention"},
        Text{"交換条件", "Bargaining"},
        Text{"檻の中", "Caged"},
        Text{"選択肢", "Choices"},
        Text{"皮肉", "Satire"},
        Text{"叱責", "Scold"},
        Text{"事件概要", "Summary"},
        Text{"言葉の牙", "Harsh Words"},
        Text{"関本の本心を探れ！", "What Sekimoto is really thinking"},
        Text{"選択肢", "Choices"},
        Text{"仲裁", "Arbitration"},
        Text{"ガイシャの正体", "Victims Identity"},
        Text{"選択肢", "Choices"},
        Text{"立花美鈴と関本爽二朗", "Misuzu & Soujiro"},
        Text{"判断", "Judgment"},
        Text{"興味", "Interest"},
        Text{"今後の方針", "Future Plan"},
        Text{"女子大生", "Uni Student"},
        Text{"選択肢", "Choices"},
        Text{"刑事告訴もの", "Criminal Complaint?"},
        Text{"リベンジ", "Revenge"},
        Text{"彼女のアリバイ", "Her Alibi"},
        Text{"砂堀酒造", "Brewery"},
        Text{"選択肢", "Choices"},
        Text{"激昂", "Indignation"},
        Text{"突発的な行動", "Spontaneous"},
        Text{"引き取り", "Acceptance"},
        Text{"閑話休題", "Digression"},
        Text{"福祉学生", "Welfare Student"},
        Text{"人物関係", "Personal Feelings"},
        Text{"選択肢", "Choices"},
        Text{"完黙再び", "Silence"},
        Text{"選択肢", "Choices"},
        Text{"選択肢", "Choices"},
        Text{"選択肢", "Choices"},
        Text{"取材記者", "Legman"},
        Text{"狐と狸の応酬", "Fox & Tanuki's Exchange"},
        Text{"津田沼を上手くコントロールせよ！", "Get Tsudanuma under control!"},
        Text{"週刊サラリー", "Weekly Salary"},
        Text{"選択肢", "Choices"},
        Text{"防犯カメラ", "Security Camera"},
        Text{"取引に乗る", "The Deal"},
        Text{"断末魔の叫び", "Screaming in Agony"},
        Text{"選択肢", "Choices"},
        Text{"方法について", "Methods"},
        Text{"遺体状況", "Corpse Status"},
        Text{"歯", "Teeth"},
        Text{"現場記録", "Field Notes"},
        Text{"金谷大夢", "Kanaya Hiromu"},
        Text{"恫喝", "Intimidation"},
        Text{"屁理屈屋の金谷を屈服させろ！", "Bring Kanaya to his knees!"},
        Text{"生命の危機", "Life-Threatening"},
        Text{"多汗症", "Hyperhidrosis"},
        Text{"張り込み", "Steakout"},
        Text{"選択肢", "Choices"},
        Text{"緊急対応", "Emergency Response"},
        Text{"増援要請", "Request for Back-up"},
        Text{"状況確認", "Checking the Situation"},
        Text{"突入", "Storming"},
        Text{"妖怪", "Yokai"},
        Text{"選択肢", "Choices"},
        Text{"先輩の勇気", "Senior Courage"},
        Text{"正直な心境", "Honest Feelings"},
        Text{"異様", "Odd"},
        Text{"山狩り", "Mountain Hunt"},
        Text{"たった二人の捜査班", "Two Investigators"},
        Text{"選択肢", "Choices"},
        Text{"ねめつける視線", "Glare"},
        Text{"五月蠅い呼吸", "Labored Breath"},
        Text{"かぶりつき", "Front-row Seats"},
        Text{"餓鬼", "Preta"},
        Text{"犯人確保", "Secure Prisoner"},
        Text{"水瀬との関係", "Relationship With Minase"},
        Text{"選択肢", "Choices"},
        Text{"歓喜", "Delight"},
        Text{"驚愕", "Shock"},
        Text{"畏怖", "Awe"},
        Text{"三文芝居", "Three Sentence Play"},
        Text{"選択肢", "Choices"},
        Text{"志願", "Desire"},
        Text{"仇討ち", "Vengeance"},
        Text{"過小評価", "Underestimation"},
        Text{"四度目の正直", "Fourth Time's the Charm"},
        Text{"事情聴取", "Interrogation"},
        Text{"金谷の心の中", "Inside Kanaya's Mind"},
        Text{"水瀬になりきって聴取せよ！", "Listen like you're Minase!"},
        Text{"憔悴の気持ち", "Exhaustion"},
        Text{"打ち切り", "Cancellation"},
        Text{"選択肢", "Choices"},
        Text{"悪あがき", "Useless Resistance"},
        Text{"悔しくて", "Annoyed"},
        Text{"薬物", "Medicines"},
        Text{"送還へ", "Deportation"},
        Text{"通達", "Directive"},
        Text{"護送", "Escort"},
        Text{"選択肢", "Choices"},
        Text{"救急車", "Ambulance"},
        Text{"緊急事態", "State of Emergency"},
        Text{"救護方法", "Relief"},
        Text{"バイタルサイン", "Vital Signs"},
        Text{"応援要請状況", "Request for Support"},
        Text{"拉致", "Kidnapping"},
        Text{"選択肢", "Choices"},
        Text{"笑顔", "Smiling"},
        Text{"理解不能の怖さ", "Scary Beyond Comprehension"},
        Text{"理解不能の感情", "Feelings I Don't Understand"},
        Text{"脱出へ", "Escape"},
        Text{"処理部屋", "Treatment Room"},
        Text{"選択肢", "Choices"},
        Text{"水瀬遥殺人事件", "Minase Haruka Murder Case"},
        Text{"ブラインドマン", "Blind Man"},
        Text{"連続殺人事件", "Serial Murders"},
        Text{"クイズの正解", "Quiz"},
        Text{"推理ロジック", "Inference Logic"},
        Text{"失敗", "Mistake"},
        Text{"告白", "Confession"},
        Text{"命乞い", "Begging for Your Life"},
        Text{"生きるために言葉で足掻け！", "Fumble your words to stay alive!"},
        Text{"鏡の中の私", "My Reflection"},
        Text{"覚悟", "Resolution"},
        Text{"東拘", "Tokyo Detention"},
        Text{"選択肢", "Choices"},
        Text{"急行", "Moving Fast"},
        Text{"嫌悪感", "Dab Feelings"},
        Text{"完黙再び", "Silence"},
        Text{"成就", "Achievements"},
        Text{"留置所の特別講義", "Special Lecture"},
        Text{"竹中慎一郎", "Takenaka"},
        Text{"鑑識の結果", "Forensics Results"},
        Text{"選択肢", "Choices"},
        Text{"選択肢", "Choices"},
        Text{"おどけた後", "After the Joke"},
        Text{"風守さんはどこへ？", "Where's Kazamori?"},
        Text{"選択肢", "Choice"},
        Text{"休憩所には？", "Where's the rest stop?"},
        Text{"特ラ課オフィスには？", "What's in the Office?"},
        Text{"まさか、あそこへ？", "You're not going in there, are you?"},
        Text{"選択肢", "Choices"},
        Text{"関本の嗅覚", "Sekimoto's Sense of Smell"},
        Text{"砂堀酒造へ", "To the Sunahori Brewery"},
        Text{"選択肢", "Choices"},
        Text{"飲み込んだ言葉", "Swallow My Words"},
        Text{"では頂きます", "Let's eat"},
        Text{"心霊写真？", "Ghost photo?"},
        Text{"選択肢", "Choices"},
        Text{"妖精事件", "Fairy Incident"},
        Text{"偶然の映像", "Accidental Video"},
        Text{"心霊写真講釈", "Ghost photo review"},
        Text{"接点の女", "Contact"},
        Text{"水瀬の信用を勝ち取れ！", "Win Minase's trust!"},
        Text{"水瀬遥の告白", "Minase's Confession"},
        Text{"閉ざす心", "Closed-minded"},
        Text{"選択肢", "Choices"},
        Text{"根気よく待つ", "Waiting patiently"},
        Text{"疑っていない", "I don't doubt that"},
        Text{"唐突の来訪", "Sudden Visit"},
        Text{"水瀬の死", "Death of Minase"},
        Text{"再び関本に", "Sekimoto, Again"},
        Text{"水瀬宅へ", "Minase's House"},
        Text{"アルバムの心霊写真", "Psychic Photo Album"},
        Text{"不審死製造機", "No Trial"},
        Text{"風守に意見を聞いて懐柔しろ！", "Ask Kazamori for his oppinion!"},
        Text{"捜査の決意", "Determination"},
        Text{"決めるなら？", "Have you decided?"},
        Text{"選択肢", "Choices"},
        Text{"やります", "I'll do it"},
        Text{"やらない", "I won't do it"},
        Text{"……もう少し", "A little more"},
        Text{"選択肢", "Choices"},
        Text{"唐突に襲いかかる", "Suddenly it Hits you"},
        Text{"３度関本と", "Three Times"},
        Text{"美鈴にも霊が？", "Misuzu Possessed?"},
        Text{"選択肢", "Choices"},
        Text{"何をしたの", "What did you do?"},
        Text{"見えているの", "I see you"},
        Text{"どうかしたの", "What's Wrong?"},
        Text{"覗く何者か", "Looking In"},
        Text{"美鈴の身辺捜査", "Misuzu's Personal Affairs"},
        Text{"美鈴の過去", "Misuzu's Past"},
        Text{"推理ロジック", "Inference Logic"},
        Text{"死霊の再訪", "Revisiting the Dead"},
        Text{"美鈴への聴取", "Misuzu's Interview"},
        Text{"選択肢", "Choices"},
        Text{"心配なの", "Worried"},
        Text{"真相を話して", "Tell me the truth"},
        Text{"立花から真相を引き出せ！", "Get the truth from Tachibana!"},
        Text{"キューピッドさん", "Cupid"},
        Text{"ならば感情に", "You're Emotional"},
        Text{"選択肢", "Choices"},
        Text{"涙ながらに", "Tears"},
        Text{"泣き喚いて", "Crying"},
        Text{"再びのメール", "Email"},
        Text{"選択肢", "Choices"},
        Text{"美鈴の最後", "Misuzu's End"},
        Text{"黒いもやが這う", "Black Mist"},
        Text{"最後の友達", "My last Friend"},
        Text{"公務中なので", "Official Business"},
        Text{"あくまで試供品として", "Just a Sample"},
        Text{"醤油の匂い", "The smell of Soy Sauce"},
        Text{"人毛醤油", "Human Hair Soy Sauce"},
        Text{"選択肢", "Choices"},
        Text{"面白半分伝説", "Half-interesting legend"},
        Text{"風評伝説", "Urban Legend Rumors"},
        Text{"理由を問われて", "Asked Why"},
        Text{"人体由来の固有", "Human Origin"},
        Text{"砂堀酒造の調査へ", "Brewery Investigation"},
        Text{"砂堀酒造の情報を聞き出せ！", "Get info on the Sunahori Brewery!"},
        Text{"何を持ちかける？", "What do you Propose?"},
        Text{"津田沼との共闘", "Tsudanuma's Struggles"},
        Text{"選択肢", "Choices"},
        Text{"愚問", "Foolish Question"},
        Text{"砂堀製品", "Sunahori Products"},
        Text{"選択肢", "Choices"},
        Text{"何故わざわざ醤油に", "Why Soy Sauce?"},
        Text{"死体なら他にも加工可", "Dead Body Process"},
        Text{"製品にする意味", "To be a Product"},
        Text{"上手く行ってないみたい", "It's Not Working"},
        Text{"本庁二課の介入", "Intervention"},
        Text{"再び砂堀将春と", "With Masaharu Again"},
        Text{"砂堀に怪しまれず誤魔化しきれ！", "How can we fake it?"},
        Text{"選択肢", "Choices"},
        Text{"バレていた", "They Knew"},
        Text{"殺人に動機", "殺Motive for Murder"},
        Text{"記者のこと", "Reporters"},
        Text{"醤油の秘密を", "Soy Sauce Secrets"},
        Text{"選択肢", "Choices"},
        Text{"一瞬の出来事", "A Moment in Time"},
        Text{"蔵の中に", "Warehouse"},
        Text{"選択肢", "Choices"},
        Text{"闇の中の扉", "Door in the Dark"},
        Text{"謎の黒い液体", "Mystery Black Liquid"},
        Text{"変わり果てた姿", "Disfigured"},
        Text{"選択肢", "Choices"},
        Text{"誰がやるか", "Who's going to do it?"},
        Text{"素直に手伝う", "I'll Help"},
        Text{"選択肢", "Choices"},
        Text{"携帯電話を探す", "Find a Cell Phone"},
        Text{"包丁を探す", "Find a Knife"},
        Text{"バケツを拾う", "Pickup the Bucket"},
        Text{"抜け穴を発見", "Loophole"},
        Text{"選択肢", "Choices"},
        Text{"そのまま出る", "Keep Going"},
        Text{"引き返すなんて", "Turning back"},
        Text{"警戒しながら", "Caution"},
        Text{"選択肢", "Choices"},
        Text{"待ち受けるもの", "What to Expect"},
        Text{"つかの間の安堵", "A Moment's Relief"},
        Text{"選択肢", "Choices"},
        Text{"脅しには乗らない", "I don't take kindly to threats"},
        Text{"承服するしか", "No other Option"},
        Text{"ダメ元で", "Risk"},
        Text{"通話終わり", "End of Call"},
        Text{"死臭の手", "Dead Hand"},
        Text{"美鈴に悟られる", "Misuzu will know"},
        Text{"選択肢", "Choices"},
        Text{"床下より", "From under the floor"},
        Text{"必死にごまかす", "Desprate to Deceive"},
        Text{"微笑む", "Smile"},
        Text{"怒り出す", "Rage"},
        Text{"結局話す", "We'll talk in the end"},
        Text{"特ラ課の決起", "Special Agent Decission"},
        Text{"檻の中と外", "In/Out of the cage"},
        Text{"対決の場へ", "Showdown"},
        Text{"推理ロジック", "Inference Logic"},
        Text{"全てが遅く", "Slow"},
        Text{"再び対峙", "Confronted"},
        Text{"時間を稼いで砂堀を揺さぶれ！", "Buy us time to get away from Sunahori!"},
        Text{"血の終焉", "Bloody End"},
        Text{"現場検証", "On-Scene Inspection"},
        Text{"極悪の選択", "Diabolical Choice"},
        Text{"選択肢", "Choices"},
        Text{"課長を指す", "Section Chief"},
        Text{"風守さんを", "Kazamori"},
        Text{"美鈴を指す", "Misuzu"},
        Text{"人殺しの餐宴", "Murderer's Banquet"},
        Text{"寄生虫の金谷大夢", "The Parasite, Kanaya"},
        Text{"調査手配", "Investigation"},
        Text{"選択肢", "Choices"},
        Text{"女々しさ", "Femininity"},
        Text{"助けを求める応援部署", "Backup department for help"},
        Text{"出発支度", "Departure"},
        Text{"死の舞踏", "Danse Macabre"},
        Text{"夜道の人形", "Doll in the Night"},
        Text{"人形の呪い", "Doll's Curse"},
        Text{"人形を確認できるように頼め！", "Ask them to check the doll!"},
        Text{"美鈴折れる", "Misuzu Breaks"},
        Text{"人形との対面", "Face-to-face with the Doll"},
        Text{"介護施設へ", "To the Nursing Home"},
        Text{"人形の消失", "Doll's Disappearance"},
        Text{"選択肢", "Choices"},
        Text{"失礼ね！", "Excuse me!"},
        Text{"わからない", "I don't know"},
        Text{"勘違いじゃないの？", "Your mistaken"},
        Text{"カメラチェック", "Camera Check"},
        Text{"署内の惨劇", "A Tragedy"},
        Text{"犯人は人形？", "The Killer's a Doll"},
        Text{"徒労の作業", "Laborious Task"},
        Text{"惨劇の酒造", "The Tragic Brewery"},
        Text{"選択肢", "Choices"},
        Text{"署に連絡を", "Call the station"},
        Text{"人形を確保に", "Secure the doll"},
        Text{"この場から離脱", "I'm out of here"},
        Text{"そして対面", "Face-to-face"},
        Text{"呪いの報告", "Report of a Curse"},
        Text{"黒田に人形の調査を了承させろ！", "Get Kuroda to agree to investigate the doll!"},
        Text{"しかし一蹴", "Rejection"},
        Text{"捜査の了承", "Approval"},
        Text{"再び牧村の元へ", "Back to Makimura"},
        Text{"呪いの術式", "The Art of the Curse"},
        Text{"選択肢", "Choices"},
        Text{"何故亘が？", "Why Watari?"},
        Text{"亘を殺す理由は？", "Why would he kill Watari?"},
        Text{"選択肢", "Choices"},
        Text{"黒田課長が犯人？", "Chief Kuroda is the culprit?"},
        Text{"風守さんが犯人？", "Kazamori is the killer?"},
        Text{"牧村さんが犯人？", "Makimura is the killer?"},
        Text{"足下から奴が", "He came from underneath"},
        Text{"推理ロジック", "Inference Logic"},
        Text{"始末屋の音", "Thrifty Sounds"},
        Text{"聞きたいこと", "I want to ask"},
        Text{"黒田が事件に関与したか見極めろ！", "Determine if Kuroda was involved in the incident!"},
        Text{"近付く物音", "Approaching Sounds"},
        Text{"黒田の豹変", "Kuroda's Change of Heart"},
        Text{"フカシは禁物", "Don't do anything rash"},
        Text{"母屋２Ｆ", "Main building 2nd floor"},
        Text{"大脱出", "The Great Escape"},
        Text{"振り出しに戻る", "To the Beginning"},
        Text{"応答ゲーム", "Response Games"},
        Text{"立花に状況を確認せよ！", "Check with Tachibana, see what's going on!"},
        Text{"総括", "Generalize"},
        Text{"浮かぶ疑問", "The one Question"},
        Text{"熱消毒", "Thermal Disinfection"},
        Text{"逃避行", "Escape Route"},
        Text{"立ち位置の確認", "Confirmation of Standing Position"},
        Text{"津田沼からの誘い", "Invitation from Tsudanuma"},
        Text{"選択肢", "Choices"},
        Text{"旅館の失踪事件", "Missing Inn"},
        Text{"異変", "Accident"},
        Text{"絶望", "Despair"},
        Text{"贖罪", "Atonement"},
        Text{"選択肢", "Choices"},
        Text{"生存者２名", "Survivor 2"},
        Text{"生存者１名", "Survivor 1"},
        Text{"発信者", "Originator"},
        Text{"関本に金谷救出を納得させろ！", "Convince Sekimoto to rescue Kanaya!"},
        Text{"地獄の光景", "A scene from hell"},
        Text{"推理ロジック", "Inference Logic"},
        Text{"帰還", "Return"},
        Text{"折れた矢", "Broken Arrow"},
        Text{"死を回避する取引をせよ！", "Make the deal that averts death!"},
        Text{"始末", "The Beginning and End"},
        Text{"炎の村", "Village of Fire"},
        Text{"忘れ物", "Forget-me-nots"},
        Text{"選択肢", "Choices"},
        Text{"ただの悪戯なら", "If this is a prank"},
        Text{"検討はすべき", "Consider it"},
        Text{"事件性はあります", "We've got a case"},
        Text{"興味のない関本", "Uninterested"},
        Text{"風守の不在", "The Absence of Kazamori"},
        Text{"選択肢", "Choices"},
        Text{"チェーンメールを", "Chain Mail"},
        Text{"週刊サラリー", "Weekly Salary"},
        Text{"現れる金谷", "Manifestation"},
        Text{"そして旅館に", "To the Inn"},
        Text{"金谷旅館の由来", "Origin of Kanaya Inn"},
        Text{"洞窟の離れ", "Hidden Grotto"},
        Text{"選択肢", "Choices"},
        Text{"何を言いかけたの", "What were you about to say?"},
        Text{"脅迫について", "Intimidation"},
        Text{"お仕事は楽しい？", "Do you enjoy your work?"},
        Text{"そして狂宴へ", "Madness"},
        Text{"立ち塞がる男", "Standing in the Way"},
        Text{"津田沼に説得を試みろ！", "Try to talk sense into Tsudanuma!"},
        Text{"命の選択を", "Choose life"},
        Text{"選択肢", "Choices"},
        Text{"永久に囚われて", "Trapped Forever"},
        Text{"不意の一撃に", "Surprise Blow"},
        Text{"繋がらないコール", "Disconnected Calls"},
        Text{"激痛", "Violent Pain"},
        Text{"無柵の檻", "Unfenced Cage"},
        Text{"最悪の朝", "Worst Morning Ever"},
        Text{"嫁に来ないか", "Will you Marry Me?"},
        Text{"選択肢", "Choices"},
        Text{"しない", "Shinai"},
        Text{"心に刃を向けてでも", "Even with a Sword in my Heart"},
        Text{"安堵と油断", "Relief and Carelessness"},
        Text{"中央ブリーフ連盟", "Central Briefing Federation"},
        Text{"切り株映像", "Stump Videos"},
        Text{"金谷の凶行を食い止めろ！", "Put a stop to Kanaya's murder!"},
        Text{"その選択を", "Make that choice"},
        Text{"選択肢", "Choices"},
        Text{"生け贄の祭殿", "Hall of Sacrifice"},
        Text{"その場逃れに", "Trying to stay out of the way"},
        Text{"選択肢", "Choices"},
        Text{"ライアーズブライド", "Liar's Bride"},
        Text{"優子の知ること", "What Yuuko Knows"},
        Text{"選択肢", "Choices"},
        Text{"優子の事情を", "Yuuko's Situation"},
        Text{"優子を罵る", "Cursing Yuuko"},
        Text{"優子に同情", "Pity Yuuko"},
        Text{"如菩薩団", "A Buddist Group"},
        Text{"風守の末路", "Kazemori's End"},
        Text{"デッドバイドーン", "Dead By Dawn"},
        Text{"選択肢", "Choices"},
        Text{"死ぬには足りない？", "Not good enough to die?"},
        Text{"死への旅路", "Journey to Death"},
        Text{"絶望と逆境からの光明", "Sunshine from Despair"},
        Text{"選択肢", "Choices"},
        Text{"最後の煩悶", "The Last Agony"},
        Text{"勝負に出る", "Take a Chance"},
        Text{"選択肢", "Choices"},
        Text{"蛇に飲まれるように", "As if Swallowed by a Snake"},
        Text{"津田沼を言い包めて難を逃れろ！", "Get out of trouble by talking down Tsudanuma!"},
        Text{"生死のジャンケン", "Rock, Paper, Scissors"},
        Text{"選択肢", "Choices"},
        Text{"何とか生存", "How To Survive"},
        Text{"どうにか生存", "Surviving Somehow"},
        Text{"負けて死ぬ", "lose and die"},
        Text{"解き放つ狂気×狂気", "Unleashing Madness x Madness"},
        Text{"推理ロジック", "Inference Logic"},
        Text{"命脈尽きて", "dying for dear life"},
        Text{"ブラッドリィウェディング", "Bloody Wedding"},
        Text{"選択肢", "Choices"},
        Text{"結婚はしない", "I'm not getting married"},
        Text{"くたばれ豚野郎", "Fuck you, you pig"},
        Text{"ニードルマニアック", "Needle Maniac"},
        Text{"見詰める金谷", "Staring"},
        Text{"死の彷徨", "Wandering of the dead"},
        Text{"ヴィデオ・ドローム", "Video Drome"},
        Text{"課長との再会", "Reunion with the Chief"},
        Text{"惨劇の終焉", "The End of the Scourge"},
        Text{"ザ・ビギニング", "The Beginning"},
        Text{"無人の警察", "Unattended"},
        Text{"死屍累々の場", "Scene of Carnage"},
        Text{"選択肢", "Choices"},
        Text{"決死の説得", "Desperate Persuasion"},
        Text{"逃げるしかない！？", "We have to get away!"},
        Text{"陥る窮地", "Unfavorable Situation"},
        Text{"この場からの脱出", "Escape This Place"},
        Text{"集団感染者", "Infected People"},
        Text{"瀕死の黒田課長", "The dying Chief Kuroda"},
        Text{"やけになった風守を冷静にさせろ！", "Get the desperate Kazamori to calm down!"},
        Text{"もはや冷静では……", "I'm no longer calm"},
        Text{"選択肢", "Choices"},
        Text{"どかない", "Unsettled"},
        Text{"どうぞどうぞ", "Here you go"},
        Text{"キレてみる", "I'm gonna snap"},
        Text{"選択肢", "Choices"},
        Text{"死角からの手", "Blind Spot"},
        Text{"潜む者の闇音", "The Dark Sound of Lurkers"},
        Text{"忘れ去られた男", "The Forgotten Man"},
        Text{"フロリダ・ゾンビ", "Florida Zombie"},
        Text{"蠢く者たちの夜明け", "Dawn of the Wriggling Ones"},
        Text{"惨劇の旅館", "Scourge of the Inn"},
        Text{"銃には頼れない", "We can't rely on guns"},
        Text{"感染者の処理方法", "How to handle infected people"},
        Text{"映像を信じる金谷を問いただせ！", "Ask Kanaya if he believes the footage!"},
        Text{"最悪なオススメ", "Worst Recommendation"},
        Text{"選択肢", "Choices"},
        Text{"追いかける", "Persue"},
        Text{"再びの対面", "Face-to-face Again"},
        Text{"引き止める", "Restrain"},
        Text{"選択肢", "Choices"},
        Text{"予行演習", "Exercises"},
        Text{"感染者狩り", "Hunting for Infected People"},
        Text{"地獄が溢れる", "Hell is Overflowing"},
        Text{"そして発症者", "Onset"},
        Text{"選択肢", "Choices"},
        Text{"役目は委ねられる", "The role will be Delegated"},
        Text{"懇願をしても……", "Make a plea"},
        Text{"そこからの逃避", "Escape"},
        Text{"猫撫で声", "Wheedling Voice"},
        Text{"家族の終焉", "The End of the Family"},
        Text{"消耗する日々", "Exhausting Days"},
        Text{"介護施設に向かう決意をさせろ！", "Make him determined to head for the nursing home!"},
        Text{"無茶に挑む", "Challenge"},
        Text{"選択肢", "Choices"},
        Text{"関本で", "Sekimoto"},
        Text{"じゃあ金谷さんで", "Kanaya"},
        Text{"多勢に無勢", "Outnumbered"},
        Text{"脱出計画", "Escape Plan"},
        Text{"出撃", "Battle"},
        Text{"誰を信じれば？", "Who to Trust"},
        Text{"選択肢", "Choices"},
        Text{"推理ロジック", "Inference Logic"},
        Text{"私の選択", "My Choices"},
        Text{"地獄のような光景", "A Hellish Scene"},
        Text{"選択は一つだけ", "Only One Choice"},
        Text{"最後の願い", "Final Wishes"},
        Text{"これから先は", "From here on out"},
        Text{"選択肢", "Choices"},
        Text{"お店って", "A Store?"},
        Text{"鳴き声って", "Whats that sound?"},
        Text{"あなたって", "Who are you?"},
        Text{"約束", "Promise"},
        Text{"楽園", "Paradise"},
        Text{"エデンの入り口", "Entrance to Eden"},
        Text{"機動隊", "Riot Police"},
        Text{"懇願", "Pettition"},
        Text{"ＮＫＰへの潜入捜査を拒絶しろ！", "Refuse to go undercover in the NKP!"},
        Text{"プランＢ", "Plan B"},
        Text{"選択肢", "Choices"},
        Text{"二人で奮闘", "Struggling Together"},
        Text{"お払い箱", "Fired"},
        Text{"採用の理由", "Reason for Adoption"},
        Text{"開き直り", "Opening Up"},
        Text{"潜入", "Infiltration"},
        Text{"選択肢", "Choices"},
        Text{"退路断つ", "Cut off Retreat"},
        Text{"邪魔者は排除", "Remove those who stand in your way"},
        Text{"負ける", "Lose"},
        Text{"妥協", "Compromise"},
        Text{"ヒロムたんを上手に接客せよ！", "Treat Hiromu-tan Well!"},
        Text{"新人研修", "Newcomer Training"},
        Text{"選択肢", "Choices"},
        Text{"貴重な経験", "Valuable Experience"},
        Text{"酷い不始末", "Terrible Mismanagement"},
        Text{"新人の頃", "When I was a Rookie"},
        Text{"謎の接客術", "Customer Service"},
        Text{"フェロモン", "Pheromone"},
        Text{"怪しむ砂堀をやり込めろ！", "Put a stop to the suspicious Sunahori!"},
        Text{"全身麻痺の不安感", "Full Body Paralysis"},
        Text{"最深部", "Depest Parts"},
        Text{"推理ロジック", "Inference Logic"},
        Text{"楽園ＮＫＰ", "Paradise NKP"},
        Text{"あともう一息", "One More Sigh"},
        Text{"感情を見せない男", "Emotionless Man"},
        Text{"カツ丼とは？", "What is Katsudon?"},
        Text{"カツ丼の効果", "Effects of Katsudon"},
        Text{"暴行目撃", "Assault Witness"},
        Text{"選択肢", "Choices"},
        Text{"虐待でしょう？", "Abusive, isn't it?"},
        Text{"拷問なんじゃ？", "Isn't that torture?"},
        Text{"見なかった事に", "Look the other way"},
        Text{"そのシステム", "That System"},
        Text{"黒田との問答", "Q&A with Kuroda"},
        Text{"黒田らの違法行為を糾弾せよ！", "Condem Kuroda's Illgal Activities!"},
        Text{"進退問題", "In & Out Questions"},
        Text{"選択肢", "Choices"},
        Text{"辞めてやる", "I'm Quitting"},
        Text{"犯行の証拠写真", "Photo evidence of the crime"},
        Text{"電気ビリビリ", "Electric Shock"},
        Text{"選択肢", "Choices"},
        Text{"スイッチに触れる", "Touching the Switch"},
        Text{"それは無理", "I can't do that"},
        Text{"電気拷問", "Electro Torture"},
        Text{"選択肢", "Choices"},
        Text{"スイッチを入れ……", "Switch on "},
        Text{"スイッチ入れません", "Refuse to switch it on"},
        Text{"電気刑", "Electric Penalty"},
        Text{"選択肢", "Choices"},
        Text{"やるしかないのか", "You have to do it"},
        Text{"電気昇天", "Electrical Phenomena"},
        Text{"一線超える", "Cross a Line"},
        Text{"ビリビリいこうぜ", "let's get Cracking"},
        Text{"関本に説得", "Persuade Sekimoto"},
        Text{"選択肢", "Choices"},
        Text{"命だいじに", "Cherish your life!"},
        Text{"死にますよ", "You're gonna die"},
        Text{"何を考えて", "What were you thinking?"},
        Text{"最後の言葉", "Last Words"},
        Text{"拷問道具", "Torture Props"},
        Text{"拷問の強要に立ち向かえ！", "Stand up to the torture coercion!"},
        Text{"何とか言うなら", "Whatever you say"},
        Text{"選択肢", "Choices"},
        Text{"辞めさせてもらいます", "I'm Resigning"},
        Text{"最後のチャンス", "Last Chance"},
        Text{"美鈴に相談", "Talk to Misuzu"},
        Text{"相談相手は消される", "Your advisor will be erased"},
        Text{"選択肢", "Choices"},
        Text{"逃げるんだ", "We gotta go"},
        Text{"闇の更にその奥底に", "Deep in the Darkness"},
        Text{"観念完了", "Contemplation"},
        Text{"最後の抵抗", "The Last Resistance"},
        Text{"拷問の強要に抵抗しろ！", "Resist the Torture!"},
        Text{"拷問するのとされるのと", "To Torture and to be Tortured"},
        Text{"選択肢", "Choices"},
        Text{"やるしかないの？", "Do I have to?"},
        Text{"身体で理解？", "Physical Understanding?"},
        Text{"じゃあドリルで", "Then Drill"},
        Text{"ドリルの力", "Power of Drill"},
        Text{"殺っちゃった", "I killed him"},
        Text{"リフレイン", "Refrain"},
        Text{"推理ロジック", "Inference Logic"},
        Text{"そして再び……", "And again"},
        Text{"笑う殺人者", "Laughing Murderer"},
        Text{"美鈴との対決", "Confrontation with Misuzu"},
        Text{"仕込めるのは誰？", "Who can we plant?"},
        Text{"食い下がり", "Lost Livelihood"},
        Text{"特ラ課出動", "Special Agent in Charge"},
        Text{"対策本部設立", "Establishment"},
        Text{"ひ……人殺し", "No Murderer"},
        Text{"急転", "Sudden Change"},
        Text{"津田沼を上手くコントロールせよ！", "Control Tsudanuma well!"},
        Text{"生命の危機", "Life-Threatening"},
        Text{"かぶりつき", "Front Row"},
        Text{"悪あがき", "Vain Struggle"},
        Text{"救急車", "Ambulance"},
        Text{"失敗", "Blunder"},
        Text{"鏡の中の私", "Me in the Mirror"},
        Text{"最後の友達", "My last friend"},
        Text{"唐突の来訪", "An unexpected visit"},
        Text{"唐突に襲いかかる", "Suddenly it hits me"},
        Text{"死霊の再訪", "Revisiting the Dead"},
        Text{"心配なの", "I'm worried"},
        Text{"泣き喚いて", "Crying"},
        Text{"黒いもやが這う", "A black miasma crawls"},
        Text{"血の終焉", "The End of Blood"},
        Text{"一瞬の出来事", "A Moment in Time"},
        Text{"素直に手伝う", "I'll help you"},
        Text{"待ち受けるもの", "What to Expect"},
        Text{"全てが遅く", "Everything's slow"},
        Text{"人殺しの餐宴", "Murderer's Banquet"},
        Text{"惨劇の終焉", "End of the Scourge"},
        Text{"永久に囚われて", "Trapped forever"},
        Text{"生け贄の祭殿", "Hall of Sacrifice"},
        Text{"死への旅路", "Journey to Death"},
        Text{"蛇に飲まれるように", "Swallowed by a snake"},
        Text{"負けて死ぬ", "Lose and Die"},
        Text{"命脈尽きて", "Dying for your life"},
        Text{"これから先は", "From here on out"},
        Text{"死角からの手", "Blind Spot"},
        Text{"再びの対面", "Face to face again"},
        Text{"そこからの逃避", "Escape from it"},
        Text{"多勢に無勢", "Outnumbered"},
        Text{"私の選択", "My Choice"},
        Text{"選択は一つだけ", "There's only one choice"},
        Text{"そして再び……", "And again"},
        Text{"辞めてやる", "I'm quitting"},
        Text{"電気昇天", "Electrical Phenomena"},
        Text{"辞めさせてもらいます", "I'm resigning"},
        Text{"闇の更にその奥底に", "Deeper Into Darkness"},
        Text{"身体で理解？", "Physical Understanding?"},
        Text{"笑う殺人者", "Laughing Murderer"},
        Text{"忘れ物", "Lost Article"},
        Text{"助けを求める応援部署", "Backup"},
        Text{"絶望", "Despair"},
        Text{"贖罪", "Atonement"},
        Text{"生存者１名", "Survivor 1"},
        Text{"折れた矢", "Broken Arrow"},
        Text{"始末", "The Beginning and End"},
        Text{"黒田の豹変", "Kuroda's change of heart"},
        Text{"この場から離脱", "I'm out of here"},
        Text{"しかし一蹴", "Rejection"},
        Text{"足下から奴が", "He's under our feet"},
        Text{"始末屋の音", "Thrifty Sounds"},
        Text{"近付く物音", "Approaching Sounds"},
        Text{"楽園ＮＫＰ", "Paradise NKP"},
        Text{"採用の理由", "Reason for Adoption"},
        Text{"負ける", "Succumb"},
        Text{"新人の頃", "When I was a rookie"},
        Text{"全身麻痺の不安感", "Full Body Paralysis"},
        Text{"あともう一息", "One More Breath"}
    };
    std::span<Text> Tree2C(Tree2C_data);

    std::array Tree4C_data = {
        Text{"疑問を口にしてみる", "I'm going to speak my mind"},
        Text{"皮肉を言う", "speak cynically"},
        Text{"答えなさい！", "Answer me!"},
        Text{"関本に会いに行く", "I'm going to see Sekimoto"},
        Text{"刑事告訴ものです", "That's a criminal complaint"},
        Text{"怒る", "Get Angry"},
        Text{"疑問を口にしてみる", "I'm going to speak my mind"},
        Text{"言葉を飲み込んだ", "Swallowed Words"},
        Text{"刑事告訴ものです", "That's a criminal complaint"},
        Text{"怒る", "Get Angry"},
        Text{"取引に乗る", "Get in on the deal"},
        Text{"殺し方がずさん", "Sloppy killing"},
        Text{"単独で飛び込む", "Dive in Solo"},
        Text{"風守さんを見た", "I saw Kazamori"},
        Text{"胸を押さえる", "Clutch your chest"},
        Text{"喜ぶ", "Be Delighted"},
        Text{"やらせて下さい", "Let me do it"},
        Text{"尋問を強行する", "Force the Interrogation"},
        Text{"救急車を呼ぶ", "Call an ambulance"},
        Text{"喜びだ", "Pleasure"},
        Text{"連続殺人事件", "Serial Killer"},
        Text{"思わず口を抑えた", "Hold my Tongue"},
        Text{"モニターを見つめた", "I stared at the monitor"},
        Text{"風守さんを見た", "I saw Kazamori"},
        Text{"休憩所", "Rest Area"},
        Text{"特ラ課オフィス", "Special Section Office"},
        Text{"では頂きます", "Let's eat"},
        Text{"偽物", "Counterfeit"},
        Text{"根気よく待つ", "Wait patiently"},
        Text{"やる", "Do it"},
        Text{"だからこそ出番だ", "That's why you're here"},
        Text{"あのさ……今なにをしたの？", "what did you just do?"},
        Text{"真相を話して", "Tell me the truth"},
        Text{"懇願する", "I beg you"},
        Text{"もやを払いのける", "Dispel Doubts"},
        Text{"ただのデタラメ", "Just bullshit"},
        Text{"情報交換をしたい", "Exchange information"},
        Text{"わざわざ醤油にする意味は？", "The point of soy sauce"},
        Text{"殺人に動機がある", "Motive for murder"},
        Text{"カマをかけてみる", "Try to trick him"},
        Text{"扉を開ける", "Open the door"},
        Text{"素直に手伝う", "I'll help you"},
        Text{"携帯電話を探す", "Find a cell phone"},
        Text{"そのまま出る", "Keep going"},
        Text{"一気に外に", "All out at once"},
        Text{"脅しには乗らない！", "I don't take kindly to threats!"},
        Text{"必死にごまかす", "desperately try to deceive"},
        Text{"黒田", "Kuroda"},
        Text{"現場に急行する", "Rush to the scene"},
        Text{"失礼ね！", "Excuse me!"},
        Text{"署に連絡", "Contact the station"},
        Text{"生みの親である亘はなぜ死んだのか？", "Why did Watari, their birth mother, die?"},
        Text{"黒田", "Kuroda"},
        Text{"自分で飲んだ", "I drank it"},
        Text{"情けをかける", "Show Mercy"},
        Text{"ただのイタズラ？", "Just a prank?"},
        Text{"風守にモーニングコール", "Kazamori's Wake-up call"},
        Text{"何を言いかけたの？", "What were you going to say?"},
        Text{"諦める", "Resign Oneself"},
        Text{"しない", "Bamboo Sword"},
        Text{"イヤ", "No"},
        Text{"首を横に振る", "Shake your head"},
        Text{"優子の事情を聞き出す", "Find out what happened to Yuuko"},
        Text{"鴨居で首をつる", "Hang from the lintel"},
        Text{"何かの合言葉？", "Code word?"},
        Text{"誰かの名前？", "Someone's name?"},
        Text{"グー", "Rock"},
        Text{"結婚はしない", "I'm not getting married"},
        Text{"呼びかける", "Call out"},
        Text{"どかない", "Unsettled"},
        Text{"冷静になろう", "Let's be cool"},
        Text{"追いかける", "Chase"},
        Text{"息を呑む", "Catch your breath"},
        Text{"金谷に思いとどまらせる", "Dissuade Kanaya"},
        Text{"関本", "Sekimoto"},
        Text{"開ける", "Open"},
        Text{"お店ってなんですか", "What's a store?"},
        Text{"じゃあ別の角度から捜査を続けます", "Continue from another angle"},
        Text{"帰るわけにはいかないんです", "I can't just leave"},
        Text{"遥さんも最初は失敗したんですか？", "Did Haruka fail at first, too?"},
        Text{"虐待でしょう？", "Abuse, right?"},
        Text{"辞める", "Quit"},
        Text{"スイッチを入れる", "Turn on the switch"},
        Text{"スイッチを入れる", "Turn on the switch"},
        Text{"やる", "Do it"},
        Text{"命を大事にして下さい", "Cherish your life"},
        Text{"辞めさせてもらいます", "I'm Resigning"},
        Text{"逃げ出す", "Escape"},
        Text{"やる", "Do it"}
    };
    std::span<Text> Tree4C(Tree4C_data);

    std::array Tree8C_data = {
        Text{"怒らせてみる", "I'll try to make him angry"},
        Text{"しかりつける", "Scold Harshly"},
        Text{"私の負けよ", "I've lost"},
        Text{"その必要はない", "No need for that"},
        Text{"復讐をするでしょう", "He'll have his revenge"},
        Text{"騒ぐ", "Be noisy"},
        Text{"怒らせてみる", "I'll try to make him angry"},
        Text{"皮肉を言う", "Speak Cynically"},
        Text{"民事賠償ものです", "Civil damages"},
        Text{"騒ぐ", "Be Noisy"},
        Text{"取引を蹴る", "Refuse the deal"},
        Text{"全裸じゃない", "They're not naked"},
        Text{"応援を呼ぶ", "Call for backup"},
        Text{"後ずさった", "They're Backpedaling"},
        Text{"口を押さえる", "Hold my tongue"},
        Text{"驚く", "Be Surprised"},
        Text{"風守さんの死を無駄にしないで下さい", "Don't let His death be in vain"},
        Text{"諦める", "Give up"},
        Text{"署からの応援を急がせる", "Get backup from the station ASAP"},
        Text{"恐怖だ", "Be Afraid"},
        Text{"ブラインドマン", "Blind Man"},
        Text{"現場に向かった", "We're on our way"},
        Text{"思わず口を抑えた", "Hold my Tongue"},
        Text{"後ずさった", "He fell back"},
        Text{"特ラ課オフィス", "Special Section Office"},
        Text{"留置所", "Jail"},
        Text{"公務中なので無理", "I can't I'm on official business"},
        Text{"偶然", "Accident"},
        Text{"疑ってはいない", "I don't doubt it"},
        Text{"やらない", "I don't do it"},
        Text{"諦める", "Give Up"},
        Text{"まさか……見えているの？", "Don't tell me you can see?"},
        Text{"疑ってるの", "I doubt it"},
        Text{"泣き喚く", "Bawl"},
        Text{"応援を呼ぶ", "Call for backup"},
        Text{"それは風評被害", "It's a rumor"},
        Text{"何か他に隠してる？", "Is there something else you're not telling me?"},
        Text{"死体の隠滅なら他にも……", "If you want to hide a body, here's something else"},
        Text{"記者のこと", "Reporters"},
        Text{"黙っていよう", "I'll keep my mouth shut"},
        Text{"逃げる手を考える", "Think of a way out"},
        Text{"誰がやるか！", "Who'll do it!"},
        Text{"包丁を探す", "Find a knife"},
        Text{"引き返す", "Retrace one's steps"},
        Text{"注意を払う", "Pay Attention"},
        Text{"……わかったわ", "I figured out"},
        Text{"微笑む", "Smirk"},
        Text{"風守", "Kazamori"},
        Text{"捜査一課に応援要請", "Requesting Backup"},
        Text{"わからない", "I don't know"},
        Text{"人形を確保", "Secure the doll"},
        Text{"亘を殺す理由は？", "Why would he kill Watari?"},
        Text{"風守", "Kazamori"},
        Text{"風守さんに飲むよう求めた", "I asked Kazamori to drink"},
        Text{"ここで恨みを晴らす", "I'll settle my grudge here"},
        Text{"検討はすべき", "Consider it"},
        Text{"風守にチェーンメール", "Kazamori's Chain Mail"},
        Text{"脅迫について何か知っているの？", "What do you know about blackmail?"},
        Text{"悲鳴をあげる", "Scream"},
        Text{"考えさせて", "Let me think"},
        Text{"そうでない", "Not really"},
        Text{"うなずく", "Nod"},
        Text{"優子を罵る", "Cursing Yuuko"},
        Text{"ドアノブで首をつる", "Hung by the doorknob"},
        Text{"店の名前？", "The name of the store?"},
        Text{"ビデオ店？", "Video store?"},
        Text{"チョキ", "Scissors"},
        Text{"くたばれ豚野郎", "Fuck you, you pig"},
        Text{"逃げ出す", "Escape"},
        Text{"どうぞどうぞ", "Here you go"},
        Text{"ガラスを片付けて", "Clear the glass"},
        Text{"引き止める", "Restrain"},
        Text{"人殺し！？", "Murderer!?"},
        Text{"風守にやめさせるように懇願する", "Beg Kazamori to stop"},
        Text{"金谷", "Kanaya"},
        Text{"開けない", "Can't open"},
        Text{"にゃんにゃんってなんですか", "What's a nyannyan?"},
        Text{"これで私はお役御免ですね", "I guess I'm off the hook now"},
        Text{"邪魔すると逮捕しますよ", "If you interfere, I'll arrest you"},
        Text{"コツとかあるんですか？", "Do you have any tips or tricks?"},
        Text{"拷問なんじゃ？", "Isn't that torture?"},
        Text{"文句を付ける", "lodge a complaint"},
        Text{"スイッチを入れない", "I'm not turning it on"},
        Text{"スイッチを入れない", "I'm not turning it on"},
        Text{"やらない", "I don't do it"},
        Text{"供述しないと死にますよ", "If you don't give a statement, you'll die"},
        Text{"それより責任問題は？", "What about liability?"},
        Text{"叫ぶ", "Scream"},
        Text{"体で理解", "Understanding through the body"}
    };
    std::span<Text> Tree8C(Tree8C_data);

    std::array TreeCC_data = {
        Text{"彼に興味はある？", "Are you interested in him?"},
        Text{"観察する", "Observe"},
        Text{"しかりつける", "Scold harshly"},
        Text{"復讐をするでしょう", "He will have his revenge"},
        Text{"おどける", "Joke"},
        Text{"歯が残っている", "Teeth still intact"},
        Text{"様子を見る", "wait and see"},
        Text{"話しかける", "Speak up"},
        Text{"怖がる", "Fear"},
        Text{"見くびらないで下さい", "Don't underestimate me"},
        Text{"応急処置を行う", "Provide first aid"},
        Text{"笑いだ", "Laughter"},
        Text{"水瀬遥殺人事件", "Minase's Murder"},
        Text{"現場に向かった", "I'm on my way to the scene"},
        Text{"力の限り叫んだ", "I screamed as hard as I could"},
        Text{"留置所", "Jail"},
        Text{"友達だと思って", "Think of me as a friend"},
        Text{"もう少し考える", "I'll think about it some more"},
        Text{"えっと……どうかしたの？", "Um what's wrong?"},
        Text{"心配なの", "I'm worried"},
        Text{"製品にする意味がない", "There is no point in making a product"},
        Text{"醤油の秘密", "Secrets of Soy Sauce"},
        Text{"バケツを拾う", "Pick up the bucket"},
        Text{"警戒する", "be cautious"},
        Text{"考えさせて", "Let me think"},
        Text{"怒り出す", "fly into a rage"},
        Text{"立花", "Woman"},
        Text{"もう一度電話をかける", "I'll call you back"},
        Text{"勘違いじゃないの？", "I think you're mistaken"},
        Text{"脱出", "Escape"},
        Text{"この人形に呪いを仕込めるのは誰だ？", "Who can put a curse on this doll?"},
        Text{"牧村", "Makimura"},
        Text{"黒田課長に飲ませる事にした", "I've decided to give it to Chief Kuroda"},
        Text{"事件性はある", "We have a case"},
        Text{"お仕事は楽しい？", "Do you enjoy your work?"},
        Text{"助けを呼ぶ", "I'll get help"},
        Text{"優子に同情する", "I feel sorry for Yuuko"},
        Text{"パー", "Paper"},
        Text{"立ち向かう", "face"},
        Text{"キレる", "lose one's temper"},
        Text{"砂堀に逃げるように叫ぶ", "Telling Kazamori to run away"},
        Text{"あなた大丈夫ですか", "Are you okay?"},
        Text{"最初からそれを採用すればいいのに", "Why not just adopt that from the start?"},
        Text{"私に負けるから怖いんでしょ", "You're afraid I'll beat you"},
        Text{"叱らないんですか？", "You're not going to scold me?"},
        Text{"見なかった事に", "pretend I didn't see it"},
        Text{"何を考えているんですか？", "What do you have in mind?"},
        Text{"本当にやるの？", "Are you sure you want to do this?"},
        Text{"観念する", "Contemplate"}
    };
    std::span<Text> TreeCC(TreeCC_data);
}